/*drop table verbe ;
create table verbe(
idverbe int primary key,
infinitif varchar(255),
preterit varchar(255),
pastperfect varchar(255),
francais varchar(255)
);

insert into verbe values
(01,'awake','awoke','awoken','se reveiller'),
(02,'be','was','been','être'),
(03,'bear','bore','borne','supporter'),
(04,'beat','beat','beaten','battre'),
(05,'become','became','become','devenir'),
(06,'begin','began','begun','commencer'),
(07,'bend','bent','bent','courber'),
(08,'bet','bet','bet','parier'),
(09,'bite','bit','bitten','mordre'),
(10,'blow','blew','blown','souffler'),
(11,'break','broke','broken','casser'),
(12,'breed','bred','bred','elever'),
(13,'bring','brought','brought','appporter'),
(14,'build','built','built','batir'),
(15,'burn','burnt','burnt','bruler'),
(16,'burst','burst','burst','eclater'),
(17,'buy','bought','bought','acheter'),
(18,'cast','cast','cast','jeter'),
(19,'catch','caught','caught','attraper'),
(20,'choose','chose','chosen','bruler'),

(21,'come','came','come','venir'),
(22,'creep','crept','crept','ramper'),
(23,'cut','cut','cut','couper'),
(24,'deal','dealt','dealt','distribuer'),
(25,'dig','dug','dug','creuser'),
(26,'do','did','done','faire'),
(27,'draw','drew','drawn','dessiner'),
(28,'dream','dreamt','dreamt','rever'),
(29,'drink','drank','drunk','boire'),
(30,'drive','drove','driven','conduire'),


(31,'eat','ate','eaten','manger'),
(32,'fall','fell','fallen','tomber'),
(33,'feed','fed','fed','nourrir'),
(34,'feel','felt','felt','sentir'),
(35,'fight','fought','fought','combatre'),
(36,'find','found','found','trouver'),
(37,'fly','flew','flown','voler'),
(38,'forbid','forbade','forbidden','interdire'),
(39,'foresee','foresaw','foreseen','prevoir'),
(40,'forget','forgot','forgotten','oublier'),

(41,'forgive','forgave','forgiven','pardonner'),
(42,'freeze','froze','frozen','geler'),
(43,'get','got','got','obtenir'),
(44,'give','gave','given','donner'),
(45,'go','went','gone','aller'),
(46,'grow','grew','grown','grandir'),
(47,'hang','hung','hung','prendre'),
(48,'have','had','had','avoir'),
(49,'hear','heard','heard','entendre'),
(50,'hide','hid','hidden','cacher'),

(61,'hit','hit','hit','frapper'),
(62,'hold','held','held','tenir'),
(63,'hurt','hurt','hurt','blesser'),
(64,'keep','kept','kept','garder'),
(65,'know','knew','known','savoir'),
(66,'lay','laid','laid','poser'),
(67,'lead','led','led','mener'),
(68,'lean','leant','leant','appuyer'),
(69,'leap','leapt','leapt','sauter'),
(70,'learn','learnt','learnt','apprendre'),

(71,'leave','left','left','quitter'),
(72,'lend','lent','lent','preter'),
(73,'let','let','let','laisser'),
(74,'lie','lay','lain','etre etendu'),
(75,'light','lit','lit','allumer'),
(76,'lose','lost','lost','perdre'),
(77,'make','made','made','fabriquer'),
(78,'mean','meant','meant','signifier'),
(79,'meet','met','met','rencontrer'),
(80,'overcome','overcame','overcome','surmonter'),
--
(81,'pay','paid','paid','payer'),
(82,'put','put','put','mettre'),
(83,'read','read','read','lire'),
--(84,'','dealt','dealt','distribuer'),
(85,'ring','rang','rung','sonner'),
(86,'rise','rose','risen','elever'),
(87,'run','ran','run','courir'),
(88,'say','said','said','dire'),
(89,'see','saw','seen','voir'),
(90,'seek','sought','sought','chercher'),

(91,'sell','sold','sold','vendre'),
(92,'send','sent','sent','envoyer'),
(93,'set','set','set','fixer'),
(94,'shake','shook','shaken','secouer'),
(95,'shine','shone','shone','briller'),
(96,'shoot','shot','shot','tirer'),
(97,'show','showed','shown','montrer'),
(98,'shut','shut','shut','rever'),
(99,'sing','sang','sung','chanter'),
(100,'sink','sank','sunk','sombrer'),

(101,'sit','sat','sat','assoir'),
(102,'sleep','slept','slept','dormir'),
(103,'smell','smelt','smelt','sentir'),
(104,'speak','spoke','spoken','parler'),
(105,'spell','spelt','spelt','epeler'),
(106,'spend','spent','spent','depenser'),
(107,'spread','spread','spread','etaler'),
(108,'spring','sprang','sprung','jaillir'),
(109,'stand','stood','stood','etre debout'),
(110,'steal','stole','stolen','voler'),


(111,'stick','stuck','stuck','coller'),
(112,'strike','struck','struck','coller'),
(113,'swear','swore','sworn','jurer'),
(114,'sweep','swept','swept','balayer'),
(115,'swim','swam','swum','nager'),
(116,'swing','swung','swung','balancer'),
(117,'take','took','taken','prendre'),
(118,'teach','taught','taught','enseigner'),
(119,'tear','tore','torn','dechirer'),
(120,'tell','told','told','dire'),

(121,'think','thought','thought','penser'),
(122,'throw','threw','thrown','lancer'),
(123,'undergo','underwent','undergone','subir'),
(124,'understand','understood','understood','comprendre'),
(125,'undo','undid','undone','defaire'),
(126,'upset','upset','upset','renverser'),
(127,'wake','woke','woken','reveiller'),
(128,'wear','wore','worn','porter'),
(129,'weep','wept','wept','pleurer'),
(130,'win','won','won','gagner'),
(131,'write','wrote','written','ecrire');
*/
--jdbc:derby://localhost:1527/sample
SELECT * FROM verbe ORDER BY RANDOM() OFFSET 0 ROWS FETCH NEXT 20 ROW ONLY
