/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verbeirregulier;

import java.awt.event.ActionEvent;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.lang.System.out;
import javax.swing.JOptionPane;

/**
 *
 * @author bonam
 */
public class Verbeirregulier extends javax.swing.JFrame {

    /**
     * Creates new form gtfgds
     */
    public Verbeirregulier() {
        createVerbe(20);

        initComponents(createlist());

    }

    public String[][] createlist() {

        out.println(listVe.length);
        Random rand = new Random();
        int nbAlea;
        String[][] str = new String[listVe.length][4];
        for (int i = 0; i < listVe.length; i++) {
            out.println("OKK");
            //Random rand = new Random();
            nbAlea = rand.nextInt(2 + 1);
            switch (nbAlea) {
                case 0:
                    str[i][0] = listVe[i].getInfinitif();
                    str[i][1] = "";
                    str[i][2] = "";
                    str[i][3] = listVe[i].getFrancais();
                    break;
                case 1:
                    str[i][0] = "";
                    str[i][1] = listVe[i].getpreterit();
                    str[i][2] = "";
                    str[i][3] = listVe[i].getFrancais();
                    break;
                case 2:
                    str[i][0] = "";
                    str[i][1] = "";
                    str[i][2] = listVe[i].getpastPerfect();
                    str[i][3] = listVe[i].getFrancais();
                    break;

                default:
                    out.println("probleme switch case");
                    exit(1);
                    break;

            }

        }
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String[][] list) {
this.setLocation(500,250);
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                list,
                new String[]{
                    "infinitif", "Preterit", "participe passé", "Francais"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Completez la liste suivante:");

        jButton2.setText("Verifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }

        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
this.setTitle("bonam swag verbs");
        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        

  
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verbeirregulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verbeirregulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verbeirregulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verbeirregulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        boolean ontinued;
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
            new Verbeirregulier().setVisible(true);
               
            }
        });
    
    }

    /*
     public String[][] createlist() {

     return new String()[][];
     }
     */
    //Class.forName("org.apache.derby.jdbc.EmbeddedDriver");

    private void jButton2ActionPerformed(ActionEvent evt) {

        new jFrRable().requete(new String[]{"1", "2", "3", " 4"}, verification());

    }

    private String[][] verification() {
        //   this.jTable1.
        String[][] str=new String[20][4];
        int j = 0;
        for (int i = 0; i < nbverbe; i++) {
            if (!(listVe[i].equals(((String) jTable1.getValueAt(i, 0)), ((String) jTable1.getValueAt(i, 1)), ((String) jTable1.getValueAt(i, 2)), ((String) jTable1.getValueAt(i, 3))))) {
                str[j][0] = listVe[i].getInfinitif();
                str[j][1] = listVe[i].getpreterit();
                str[j][2] =listVe[i].getpastPerfect();
                str[j][3] = listVe[i].getFrancais();
            j++;
            } else {
                out.print("bon");
            }
        }
          JOptionPane.showMessageDialog (null, "vous avez: "+ j+ " erreurs", " ", JOptionPane.INFORMATION_MESSAGE);
        return str;
    }

    private void createVerbe(int j) {
        String sid = "select *,random()*100 as cool from verbe\n" +
"order by cool limit "+j +";";
        int i = 0;
       /* try {
            //try in bdd
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            String url = "jdbc:derby://localhost:1527/sample";*/
    Connection c = null;
    try {
      Class.forName("org.sqlite.JDBC");
      c = DriverManager.getConnection("jdbc:sqlite:test.db");
 
  
            //Class.forName("org.postgresql.Driver");
            //Class.forName("org.postgresql.Driver");
            // DriverManager.register(new org.postgresql.Driver());
            //String url = "jdbc:postgresql:bounam";
           /* String user = "app"; //"bonam";
            String passwd = "app";//"bonam";//log don t touch

            Connection con = DriverManager.getConnection(url, user, passwd);
*/
            Statement stmt = c.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(sid);
      
      

//System.out.println("OOKKK");

  String[][] result = new String[4][nbverbe];// avec un arrayList ->perme
           listVe = new Verbe[nbverbe];//            out.println("HEY");
            while (rs.next()) {
                // out.println(i);
                listVe[i] = new Verbe(rs.getString("infinitif"),
                        rs.getString("preterit"),
                        rs.getString("pastperfect"),
                        rs.getString("francais"));
                i++;

            }

        } catch (SQLException ex) {
            Logger.getLogger(Verbeirregulier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Verbeirregulier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private int nbverbe = 20;
    private Verbe[] listVe = null;
// End o

    /**
     * @param args the command line arguments
     */
}
